require 'colorize'
require 'benchmark'

task :default => [:run]

desc "Solving problems!"
task "run" do
  $LOAD_PATH.unshift(File.dirname(__FILE__), "lib")
  require 'problem1'
  require 'look_prime'
  require 'problem2'

  MIL = 1000000
  TWO_MIL = 2000000

  primes_under_max = most_cons_prime = 0
  pb1_benchmark = Benchmark.measure do
    primes_under_max = MyPrimes.new(TWO_MIL).primes
  end

  pb2_benchmark = Benchmark.measure do
    most_cons_prime = Problem2.new(MIL).prime_under_max_has_most_cons_primes
  end

  puts "Problem#1:".red
  puts "Sum of all the primes below 2 million: ".blue << "#{primes_under_max.inject(:+)}".blue
  puts pb1_benchmark

  puts "Problem#2:".red
  puts "The prime, below one million, can be written as the sum of the most consecutive primes: ".blue <<  "#{most_cons_prime}".red
  puts pb2_benchmark
end
